name: battery_web
version: 0.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: BatteryPlugin
        fileName: battery_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"